version: '2.4'

services: 
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    restart: unless-stopped
    tty: true

  redis:
    image: eqalpha/keydb
    restart: unless-stopped
    command: ["keydb-server", "--appendonly", "yes", "--protected-mode", "no"]
    volumes:
      - "redis_data:/data"
    ports: 
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s

  postgres:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=mcutils
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=
    volumes: 
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcutils"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: